inherit_mode:
  merge:
    - Exclude

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'

Style/StringLiterals:
  EnforcedStyle: single_quotes

Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: no_space

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/RedundantReturn:
  Enabled: true
